### ISSUE TITLE
Additional Missing Data from Datamyx UI

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-datamyx#1]
Missing from UI / Mapping:
CITY
CENSUS 2
CENSUS 4

(The following are custom. Not sure how to bug these)
Datamyx Bridgeview Seg
Datamyx Bridgeview Seg Z4

**Comment by alexkwolfe** [comment]
I'm not sure the census fields are standard, but I can add them.

**Comment by kcaponeAP** [comment]
An interesting question. Would different datamyx accounts be configured to return different results. Is there a way to display all?

**Comment by alexkwolfe** [comment]
Yes. Different accounts return different data. It's customized per account. There is no way to display all of them. 

You can always create a mapping by typing in the appended data's field name (i.e. `datamyx.bridgeview_seg_z4`)

**Comment by kcaponeAP** [comment]
thanks thats very helpful.

**Comment by alexkwolfe** [comment]
Fixed in 50470fb53537ca0a81b20a92be7647594a7436a8. This has been deployed to production.

**Comment by kcaponeAP** [comment]
I do not see City in the dropdown for mappings. Can you assist?

**Comment by alexkwolfe** [comment]
It's fixed now. There was a problem with the deployment.

**Comment by kcaponeAP** [comment]
For datamyx.bridgeview_seg_z4 i can add it, but I can't make any rules against it. I need to do the following:

Map VALOAN to velocify.custom.SEG 
if datamyx.bridgeview_seg_z4 = A8..

So what's missing is that datamyx.bridgeiew_seg_24 is not in the 'if' statement drop down.

New issue?
