### ISSUE TITLE
Please add a description to Datamyx in the enhance menu

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-datamyx#5]
The datamyx description is missing from the enhancement menu.  See how the Webbula integration has a blurb under it. We are hoping to have something in there :) 

Does it also need any other icons as well? Dollar sign, mail? Not sure what those are.

![screen shot 2015-06-04 at 10 35 48 am](https://cloud.githubusercontent.com/assets/8238417/7987847/b6a61268-0aa5-11e5-9343-1378b05ef195.png)

per steve :)

**Comment by cgrayson** [comment]
This info is hardcoded in the UI for now, so I opened a client issue for this.
